### ISSUE TITLE
Temporary disconnect caused Exception in Server Tick Loop

### ISSUE THREAD

**Issue by McKitten** [GeheimagentNr1/DiscordIntegration#10]
Minecraft Version: 1.16.5
FML Version: 36.2
Mod Version: 2.1.1
Appended to ATM 6 - 1.8.3

https://gist.github.com/McKitten/e5392ef111c22987a537bc2e83ef532f

Both of my remote servers lost internet a few hours ago and while the 1.17 / java 16 machine bounced back fine the other didn't. Login revealed that the modpack had crashed in that time over discord issues and hung. No clean shutdown so no auto-reboot.

**Comment by McKitten** [comment]
It is possible the hung shutdown is a separate issue as there was no crash report this time.
Discord recorded a shutdown at its allotted time but it had in fact hung again with no visible errors this time.
I've increased the ram to the server with hopes it will resolve that one but I am (still) wishing out for a pack update at the same time.

**Comment by GeheimagentNr1** [comment]
The mod only can start, if the server has a connection to the DNS server/internet.  
Your issue (UnknownHostException) occurred, because the host (Discord URL) could not be resolved.  
But the only idea, I would have to solve this, would be, to disable the Discord Integration mod until the next restart of the server.  
  
Servers with this mod usually take about 30 seconds, sometimes longer, to stop, to disconnect from the Discord API.
