### ISSUE TITLE
Admin commands only?

### ISSUE THREAD

**Issue by igotfits1** [GeheimagentNr1/DiscordIntegration#18]
Hi can you add admin only commands, maybe have an option for a group ID that can trigger commands like the ones it has listed now but more power like shutdown, kick, etc… would be awesome!

┆Issue is synchronized with this [Trello card](https://trello.com/c/2yS0P9eE) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Released</td></tr><tr><th>Issue type:</th><td>New Feature</td></tr><tr><th>Fix type:</th><td>New feature</td></tr><tr><th>Fix version:</th><td>3.0.0</td></tr><tr><th>Fix release date:</th><td>12.11.2023</td></tr></tbody></table>

**TODOs:**

*   [x] Add flag to the command configuration, so that for every command it can be configured, if it is a management (admin) command or not.

**Comment by GeheimagentNr1** [comment]
Implemented with version 3.0.0 for Minecraft 1.18.1, 1.18.2, 1.19.2, 1.19.4 and 1.20.2
CurseForge: https://www.curseforge.com/minecraft/mc-mods/discord-integration
Modrith: https://modrinth.com/mod/discord-integration-(di)
