### ISSUE TITLE
Make discord usernames easily mentionable

### ISSUE THREAD

**Issue by AbzZero** [GeheimagentNr1/DiscordIntegration#23]
**Is your feature request related to a problem? Please describe.**
It is difficult to mention users on discord in-game since we need to type it in the format of <@user ID> for it to function correctly.

**Describe the solution you'd like**
The ability to click on the username part of a discord message to automatically type the mention in chat, but not automatically send.

**Describe alternatives you've considered**
Somehow make it possible to mention users with in @name or @name#tag format.

**Additional context**
It might help to have a config to toggle this on and off.

**Comment by GeheimagentNr1** [comment]
This is not exactly possible, because if two users have the same user or nickname, the user cannot be identified, without making mistakes. Additional for every message would multiple requests to the Discord API would be needed, what could cause performance issue and that the message takes longer to be sent.
