### ISSUE TITLE
Move config file out of serverconfig and into regular config

### ISSUE THREAD

**Issue by Deliphin** [GeheimagentNr1/DiscordIntegration#27]
**Is your feature request related to a problem? Please describe.**
It makes sense for some mods to place their configs in the world\serverconfig\ folder, because what they're handling is possibly world specific. That doesn't apply to discordintegration, this is very much not a world thing.
If I want to post my world to the internet or send it to a friend, my bot token will be made public if I don't know to remove the config file. But if it was in the regular config folder, it couldn't accidentally be leaked.

**Describe the solution you'd like**
Move the discordintegration.toml from \world\serverconfig\ to \config\

**Additional context**
I'm honestly really curious why it's in this folder to begin with. I've never seen a mod that contains sensitive data in its config, put that config file in \world\serverconfig\
Also, if it matters, I'm on 1.18.2.

┆Issue is synchronized with this [Trello card](https://trello.com/c/prVT53ZY) by [Unito](https://www.unito.io)

**Comment by GeheimagentNr1** [comment]
Moving the config from serverconfig to the config directory, is not the perfect solution either! If you build a modpack server first, it can cause issues as wel, because if the config directory is copied from the server to the client, there will the same issue, like you described with sharing the world.

Building modpack servers first is probably more used, than sharing of worlds, and additionally the bot token can be easily regenerated on the [Discord Developers Site](https://discord.com/developers/applications) page, if the bot token is shared by accident. Because of that, the config will not be moved. 

A note has been added to the mod description.
